version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest-clean
    volumes:
      - ./data/pg:/data/postgres